backend:
  image:
    repository: acrtodosopra.azurecr.io/todo-backend
    tag: latest
  replicas: 1
  port: 8081

frontend:
  image:
    repository: acrtodosopra.azurecr.io/todo-frontend
    tag: latest
  replicas: 1
  port: 80

ingress:
  enabled: false
  host: todo.example.com