backend:
  replicas: 1
  image:
    repository: acrstagingpfe2026.azurecr.io/todo-backend
    # Tag immuable attendu: le pipeline CI remplace cette valeur par un SHA Git.
    tag: "8aaa32e12ef166e74dff96947e916e966fec4b8d"
frontend:
  replicas: 1
  image:
    repository: acrstagingpfe2026.azurecr.io/todo-frontend
    # Tag immuable attendu: le pipeline CI remplace cette valeur par un SHA Git.
    tag: "8aaa32e12ef166e74dff96947e916e966fec4b8d"
ingress:
  enabled: false
  host: todo-staging.example.com
