registry:
  host: ""
  repository: ""

backend:
  image:
    name: hr-backend
    tag: "UNSET"
  replicas: 1
  port: 8081
  database:
    enabled: false
    secretName: ""
    cnpgClusterName: ""
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

frontend:
  image:
    name: hr-frontend
    tag: "UNSET"
  replicas: 1
  port: 80
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "200m"
      memory: "128Mi"

ingress:
  enabled: false
  host: ""
  staticIpName: ""
  tls:
    enabled: false
    secretName: ""
    issuerName: ""

networkPolicy:
  enabled: true
