registry:
  host: europe-west1-docker.pkg.dev
  repository: pfe-2026-495220/registry-staging-pfe
backend:
  replicas: 1
  image:
    name: hr-backend
    tag: "228b1f3"
  autoscaling:
    enabled: true
  database:
    enabled: true
    secretName: "pg-staging-app"
frontend:
  replicas: 1
  image:
    name: hr-frontend
    tag: "228b1f3"
ingress:
  enabled: false
  host: hr-staging.example.com
networkPolicy:
  enabled: true
  dnsClusterIP: "34.118.224.10"
