registry:
  host: europe-west1-docker.pkg.dev
  repository: pfe-2026-495220/registry-staging-pfe
backend:
  replicas: 1
  image:
    name: hr-backend
    tag: "4af21b7"
  autoscaling:
    enabled: false
  database:
    enabled: true
    secretName: "pg-dev-app"
    cnpgClusterName: "pg-dev"
frontend:
  replicas: 1
  image:
    name: hr-frontend
    tag: "101e02c"
ingress:
  enabled: false
  host: hr-dev.local
  staticIpName: ip-hr-dev
networkPolicy:
  enabled: true
