registry:
  host: europe-west1-docker.pkg.dev
  repository: pfe-2026-495220/registry-prod-pfe
backend:
  replicas: 2
  image:
    name: hr-backend
    tag: "v2.1.0"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
  database:
    enabled: true
    secretName: "pg-prod-app"
    cnpgClusterName: "pg-prod"
frontend:
  replicas: 2
  image:
    name: hr-frontend
    tag: "v2.1.0"
ingress:
  enabled: true
  host: hr4youp.com
  staticIpName: ip-hr-prod
networkPolicy:
  enabled: true
