registry:
  host: europe-west1-docker.pkg.dev
  repository: pfe-2026-495220/registry-staging-pfe
backend:
  replicas: 2
  image:
    name: hr-backend
    tag: "b5a0cca"
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
  pdb:
    enabled: true
    minAvailable: 1
  database:
    enabled: true
    secretName: "pg-staging-app"
    cnpgClusterName: "pg-staging"
frontend:
  replicas: 1
  image:
    name: hr-frontend
    tag: "05d02eb"
ingress:
  enabled: true
  host: hr4you.com
  staticIpName: ip-hr-staging
  tls:
    enabled: true
    secretName: hr-staging-tls
    issuerName: local-ca-issuer
networkPolicy:
  enabled: true
