registry:
  host: europe-west1-docker.pkg.dev
  repository: pfe-2026-495220/registry-staging-pfe
backend:
  replicas: 1
  image:
    name: hr-backend
    tag: "e651d30"
frontend:
  replicas: 1
  image:
    name: hr-frontend
    tag: "e651d30"
ingress:
  enabled: false
  host: hr-staging.example.com
networkPolicy:
  enabled: true
