apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    app: hr-frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: hr-frontend
  template:
    metadata:
      labels:
        app: hr-frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.registry.host }}/{{ .Values.registry.repository }}/{{ .Values.frontend.image.name }}:{{ .Values.frontend.image.tag }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- .Values.frontend.resources | toYaml | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 5
