{{- if .Values.ingress.tls.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.ingress.tls.managedCertificateName }}
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ .Values.ingress.host }}
{{- end }}
