{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hr-frontend
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: hr-frontend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.frontend.port }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: hr-backend
      ports:
        - protocol: TCP
          port: {{ .Values.backend.port }}
    - to:
        - ipBlock:
            cidr: {{ .Values.networkPolicy.dnsClusterIP }}/32
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}
