{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: postgres
type: Opaque
stringData:
  database: {{ .Values.postgres.auth.database | quote }}
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
