apiVersion: v1
kind: Service
metadata:
  name: hr-frontend
  namespace: {{ .Release.Namespace }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: hr-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}