apiVersion: v1
kind: Service
metadata:
  name: hr-frontend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hr-frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}