apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hr-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mariemmehri/repo-config
    targetRevision: main
    path: charts/hr-app
    helm:
      valueFiles:
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status/terminatingReplicas
        - /spec/replicas
    - group: networking.k8s.io
      kind: Ingress
      jsonPointers:
        - /metadata/annotations
        - /metadata/finalizers
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
