apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: todo-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: {{ .Values.backend.port }}